import { IngredientCategory } from '../common/enums/ingredient-category.enum';
import { DemoInventoryPack } from './demo-inventory.types';

/** Catalog demo-store — tồn kho & HSD giống quán thật */
export const STORE_DEMO_PACK: DemoInventoryPack = {
  ingredients: [
    { name: 'Nước trà đen (pha sẵn)', category: IngredientCategory.LIQUID, sku: 'ST-TRA-DEN', shelfLifeDays: 3 },
    { name: 'Nước trà xanh (pha sẵn)', category: IngredientCategory.LIQUID, sku: 'ST-TRA-XANH', shelfLifeDays: 3 },
    { name: 'Nước lọc', category: IngredientCategory.LIQUID, sku: 'ST-LOC', shelfLifeDays: 30 },
    { name: 'Sữa tươi', category: IngredientCategory.LIQUID, sku: 'ST-SUA-TUOI', shelfLifeDays: 5 },
    { name: 'Sữa đặc', category: IngredientCategory.LIQUID, sku: 'ST-SUA-DAC', shelfLifeDays: 14 },
    { name: 'Syrup đào', category: IngredientCategory.LIQUID, sku: 'ST-SYRUP-DAO', shelfLifeDays: 90 },
    { name: 'Syrup vải', category: IngredientCategory.LIQUID, sku: 'ST-SYRUP-VAI', shelfLifeDays: 90 },
    { name: 'Đường', category: IngredientCategory.DRY, sku: 'ST-DUONG', shelfLifeDays: 365 },
    { name: 'Đường đen (đường phèn)', category: IngredientCategory.DRY, sku: 'ST-DUONG-DEN', shelfLifeDays: 180 },
    { name: 'Bột matcha', category: IngredientCategory.DRY, sku: 'ST-MATCHA', shelfLifeDays: 180 },
    { name: 'Bột cacao', category: IngredientCategory.DRY, sku: 'ST-CACAO', shelfLifeDays: 180 },
    { name: 'Cà phê rang xay', category: IngredientCategory.DRY, sku: 'ST-CAFE', shelfLifeDays: 30 },
    { name: 'Kem cheese', category: IngredientCategory.DRY, sku: 'ST-KEM-CHEESE', shelfLifeDays: 7 },
    { name: 'Trân châu đen', category: IngredientCategory.TOPPING, sku: 'ST-TC-DEN', shelfLifeDays: 2 },
    { name: 'Trân châu trắng', category: IngredientCategory.TOPPING, sku: 'ST-TC-TRANG', shelfLifeDays: 2 },
    { name: 'Thạch dừa', category: IngredientCategory.TOPPING, sku: 'ST-THACH-DUA', shelfLifeDays: 5 },
    { name: 'Đá viên', category: IngredientCategory.OTHER, sku: 'ST-DA' },
  ],
  stockByWarehouse: {
    KHO_TONG: [
      { ingredient: 'Nước trà đen (pha sẵn)', currentStock: 120_000, minStock: 20_000 },
      { ingredient: 'Nước trà xanh (pha sẵn)', currentStock: 95_000, minStock: 18_000 },
      { ingredient: 'Sữa tươi', currentStock: 85_000, minStock: 15_000 },
      { ingredient: 'Sữa đặc', currentStock: 42_000, minStock: 6_000 },
      { ingredient: 'Đường', currentStock: 32_000, minStock: 4_000 },
      { ingredient: 'Đường đen (đường phèn)', currentStock: 15_000, minStock: 2_500 },
      { ingredient: 'Bột matcha', currentStock: 6_500, minStock: 1_200 },
      { ingredient: 'Bột cacao', currentStock: 4_800, minStock: 900 },
      { ingredient: 'Trân châu đen', currentStock: 18_000, minStock: 2_500 },
      { ingredient: 'Trân châu trắng', currentStock: 8_000, minStock: 1_500 },
      { ingredient: 'Syrup đào', currentStock: 24_000, minStock: 4_000 },
      { ingredient: 'Syrup vải', currentStock: 20_000, minStock: 3_500 },
      { ingredient: 'Cà phê rang xay', currentStock: 3_500, minStock: 800 },
      { ingredient: 'Kem cheese', currentStock: 3_200, minStock: 700 },
      { ingredient: 'Thạch dừa', currentStock: 6_000, minStock: 1_000 },
    ],
    KHO1: [
      { ingredient: 'Nước trà đen (pha sẵn)', currentStock: 68_000, minStock: 15_000 },
      { ingredient: 'Nước trà xanh (pha sẵn)', currentStock: 52_000, minStock: 12_000 },
      { ingredient: 'Sữa tươi', currentStock: 28_000, minStock: 8_000 },
      { ingredient: 'Trân châu đen', currentStock: 8_200, minStock: 1_800 },
      { ingredient: 'Thạch dừa', currentStock: 5_400, minStock: 1_000 },
      { ingredient: 'Đá viên', currentStock: 62_000, minStock: 10_000 },
      { ingredient: 'Bột matcha', currentStock: 2_200, minStock: 500 },
      { ingredient: 'Đường', currentStock: 4_500, minStock: 1_000 },
    ],
    KHO2: [
      { ingredient: 'Cà phê rang xay', currentStock: 4_200, minStock: 1_000 },
      { ingredient: 'Bột cacao', currentStock: 5_100, minStock: 900 },
      { ingredient: 'Kem cheese', currentStock: 2_800, minStock: 700 },
      { ingredient: 'Bột matcha', currentStock: 1_500, minStock: 400 },
    ],
    KHO3: [
      { ingredient: 'Syrup đào', currentStock: 18_000, minStock: 4_000 },
      { ingredient: 'Syrup vải', currentStock: 14_500, minStock: 3_500 },
      { ingredient: 'Sữa tươi', currentStock: 22_000, minStock: 6_000 },
      { ingredient: 'Sữa đặc', currentStock: 12_000, minStock: 3_000 },
    ],
  },
  toppings: [
    { name: 'Trân châu đen', price: 5_000, sortOrder: 1 },
    { name: 'Trân châu trắng', price: 5_000, sortOrder: 2 },
    { name: 'Thạch dừa', price: 5_000, sortOrder: 3 },
    { name: 'Kem cheese', price: 8_000, sortOrder: 4 },
  ],
  menuItems: [
    {
      name: '[Store] Trà sữa signature',
      category: 'Trà sữa',
      price: 32_000,
      description: 'Best seller cửa hàng — trân châu đen',
      imageUrl: '/menu/tra-sua-tran-chau.jpg',
    },
    {
      name: '[Store] Trà sữa matcha',
      category: 'Trà sữa',
      price: 38_000,
      description: 'Matcha béo, size quán',
      imageUrl: '/menu/tra-sua-matcha.jpg',
    },
    {
      name: '[Store] Trà sữa oolong',
      category: 'Trà sữa',
      price: 30_000,
      description: 'Oolong thanh nhẹ',
      imageUrl: '/menu/tra-sua-oolong.jpg',
    },
    {
      name: '[Store] Trà đào cam sả',
      category: 'Trà trái cây',
      price: 42_000,
      description: 'Đào + cam + sả',
      imageUrl: '/menu/tra-dao-cam-sa.jpg',
    },
    {
      name: '[Store] Trà vải',
      category: 'Trà trái cây',
      price: 40_000,
      description: 'Vải ngọt mát',
      imageUrl: '/menu/tra-vai.jpg',
    },
    {
      name: '[Store] Hồng trà kem cheese',
      category: 'Kem cheese',
      price: 45_000,
      description: 'Kem cheese mặn ngọt',
      imageUrl: '/menu/hong-tra-kem-cheese.jpg',
    },
    {
      name: '[Store] Cacao sữa',
      category: 'Cacao',
      price: 34_000,
      description: 'Cacao đậm vị',
      imageUrl: '/menu/cacao-sua.jpg',
    },
    {
      name: '[Store] Cà phê sữa đá',
      category: 'Cà phê',
      price: 28_000,
      description: 'Cà phê phin truyền thống',
      imageUrl: '/menu/ca-phe-sua-da.jpg',
    },
  ],
  recipes: [
    {
      menuName: '[Store] Trà sữa signature',
      lines: [
        { ingredient: 'Nước trà đen (pha sẵn)', quantity: 180 },
        { ingredient: 'Sữa tươi', quantity: 110 },
        { ingredient: 'Đường đen (đường phèn)', quantity: 30 },
        { ingredient: 'Trân châu đen', quantity: 45 },
        { ingredient: 'Đá viên', quantity: 140 },
      ],
    },
    {
      menuName: '[Store] Trà sữa matcha',
      lines: [
        { ingredient: 'Nước lọc', quantity: 90 },
        { ingredient: 'Sữa tươi', quantity: 140 },
        { ingredient: 'Bột matcha', quantity: 7 },
        { ingredient: 'Đường', quantity: 22 },
        { ingredient: 'Đá viên', quantity: 140 },
      ],
    },
    {
      menuName: '[Store] Trà sữa oolong',
      lines: [
        { ingredient: 'Nước trà đen (pha sẵn)', quantity: 190 },
        { ingredient: 'Sữa tươi', quantity: 95 },
        { ingredient: 'Đường', quantity: 16 },
        { ingredient: 'Trân châu đen', quantity: 40 },
        { ingredient: 'Đá viên', quantity: 130 },
      ],
    },
    {
      menuName: '[Store] Trà đào cam sả',
      lines: [
        { ingredient: 'Nước trà xanh (pha sẵn)', quantity: 190 },
        { ingredient: 'Syrup đào', quantity: 42 },
        { ingredient: 'Đường', quantity: 12 },
        { ingredient: 'Đá viên', quantity: 170 },
      ],
    },
    {
      menuName: '[Store] Trà vải',
      lines: [
        { ingredient: 'Nước trà xanh (pha sẵn)', quantity: 190 },
        { ingredient: 'Syrup vải', quantity: 38 },
        { ingredient: 'Đường', quantity: 10 },
        { ingredient: 'Đá viên', quantity: 160 },
      ],
    },
    {
      menuName: '[Store] Hồng trà kem cheese',
      lines: [
        { ingredient: 'Nước trà đen (pha sẵn)', quantity: 210 },
        { ingredient: 'Kem cheese', quantity: 36 },
        { ingredient: 'Đường', quantity: 18 },
        { ingredient: 'Đá viên', quantity: 110 },
      ],
    },
    {
      menuName: '[Store] Cacao sữa',
      lines: [
        { ingredient: 'Bột cacao', quantity: 16 },
        { ingredient: 'Sữa tươi', quantity: 190 },
        { ingredient: 'Đường', quantity: 16 },
        { ingredient: 'Đá viên', quantity: 95 },
      ],
    },
    {
      menuName: '[Store] Cà phê sữa đá',
      lines: [
        { ingredient: 'Cà phê rang xay', quantity: 16 },
        { ingredient: 'Nước lọc', quantity: 75 },
        { ingredient: 'Sữa đặc', quantity: 32 },
        { ingredient: 'Đá viên', quantity: 110 },
      ],
    },
  ],
  supplierReceipt: {
    supplierName: 'Cty CP Nguyên liệu Trà Sữa Miền Nam',
    documentNumber: 'STORE-NCC-2026-001',
    warehouseCode: 'KHO_TONG',
    note: 'Nhập đầu tháng — sữa, trân châu, matcha (đã ghi tồn KHO_TONG)',
    lines: [
      { ingredient: 'Sữa tươi', quantity: 40_000, unitPrice: 32, expiryDaysFromReceipt: 5 },
      { ingredient: 'Trân châu đen', quantity: 8_000, unitPrice: 82_000, expiryDaysFromReceipt: 2 },
      { ingredient: 'Bột matcha', quantity: 3_000, unitPrice: 410_000, expiryDaysFromReceipt: 120 },
      { ingredient: 'Sữa đặc', quantity: 18_000, unitPrice: 27_000, expiryDaysFromReceipt: 14 },
    ],
  },
};
